spring:
  application:
    name: service-web
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        tags: client-/${spring.application.name}
        instanceId: ${spring.application.name}:${server.port}

  datasource:
    url: jdbc:mysql://localhost:3306/web_main_db?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

feign:
  hystrix:
    enabled: true

server:
  port: 8080


