spring:
  application:
    name: service-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        tags: client-/${spring.application.name}
        instanceId: ${spring.application.name}:${server.port}
    gateway:
      routes:
        - id: test
          uri: http://localhost:8080/test
          predicates:
            - Path=/test/**

server:
  port: 5500


